### ISSUE TITLE
.m4a encoding error

### ISSUE THREAD

**Issue by danskrz** [MattMcManis/Axiom#12]
I get an issue when trying to encode from any source audio file to .m4a.

Requested output format 'm4a' is not a suitable output format
D:\File.m4a: Invalid argument

I can make it work by changing -f m4a to -f adts 

While this works nearly perfectly it results in extra time being added to the file, for example 01:00:00 became 01:36:48 and I'm not sure why.

I also tried the 'Cut' option which added -ss 00:00:00.000 -to 00:01:00.000 to the script but it results in the same issue.

**Comment by MattMcManis** [comment]
I've not been able to work on the program for a while. I've removed the `-f m4a` for .m4a format and released an update. Try without to see if it fixes the timing problem.
