### ISSUE TITLE
Feature request: save current configuration as a new preset

### ISSUE THREAD

**Issue by lucaspottersky** [MattMcManis/Axiom#13]
Would it be possible to save a preset with the current settings?

So, for example, I'd like to have a preset that always converts the Audio to OGG, 44.1khz 192kbps...

thanks for the great project =)

**Comment by MattMcManis** [comment]
Thanks. Currently it is not possible to save a custom preset. But I'm working on a new version of the program and have some code that can create an ini file for saved presets. This may take a while, I have to map every button and option to the ini exporter.

**Comment by MattMcManis** [comment]
@lucaspottersky 

I've added the ability to save custom presets in v1.7.0.

---

### 1. 

Select your settings, then press the **Save** button.

![](https://i.imgur.com/iGc01Wv.png)

If this is the first time, it will prompt to automatically create the presets file folder.

The file browser will open, name your preset and it will save the `.ini` to  
`C:\Users\Name\AppData\Local\Axiom UI\presets\`. 

---

### 2. 
If you want to look at the `.ini` files, you can open this location quickly  from the **Settings Tab** by clicking on the Preset label.

![](https://i.imgur.com/n30r4Po.png)

---

### 3. 
The new Preset will appear under the **Custom** category in the menu.

![](https://i.imgur.com/v52aZSt.png)
---

Let me know how it works for you.

**Comment by lucaspottersky** [comment]
thanks so much for the good work!
