### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by Pedroxam** [MattMcManis/Axiom#22]
Hello,
@MattMcManis
is it possible for you to create something similar to the same software but much lighter and also have an some tutorial for eg: changing user interface?
Thanks. I have used this software for a long time and it's great.

**Comment by MattMcManis** [comment]
Hi, thanks for using Axiom.

You want to edit the buttons and dropdown menus on the interface?

The interface options are hardcoded in C# and are not able to be changed unless you edit the source code And then compile the program with Visual Studio.

What options on the interface do you want to change?

**Comment by Pedroxam** [comment]
In fact, I want to be able to add a new theme. and this theme can be apply in the settings.
And one more thing, I want to know how to add a new tool. For example, a tool for saving online m3u8 videos.( i always use the one ffmpeg parameter for this  ).
so, i need to make new tab, one textbox and saving button.

Anyway,
I'm glad if you can tell me which software is needed for this. (my works is mostly with web programming and I'm not familiar with this softwares.)
Thankful

**Comment by MattMcManis** [comment]
This may be hard to do, the program code is very large. I am the only developer of the program and have not yet written a full Wiki on how it all works. It could take a long time for someone new to figure out how to make changes.

It will probably be too difficult add an m3u8 downloader. But I have added the [youtube-dl](https://ytdl-org.github.io/youtube-dl/index.html) option, which might detect m3u8 files. You can generate a script and edit it by changing mp4 to m3u8 and press Run.

I have a few program diagrams on the Wiki
https://github.com/MattMcManis/Axiom/wiki
https://github.com/MattMcManis/Axiom/wiki/Controls
https://github.com/MattMcManis/Axiom/wiki/Controls-Priority-Order
https://github.com/MattMcManis/Axiom/wiki/Order-of-Operations

---

You need **Visual Studio** 
https://visualstudio.microsoft.com/vs/community

---

Here are Axiom's source files. 
https://github.com/MattMcManis/Axiom/tree/master/source/Axiom/Axiom

---

**Main Window** GUI
Tabs are here in `XAML`
https://github.com/MattMcManis/Axiom/blob/master/source/Axiom/Axiom/MainWindow.xaml
https://github.com/MattMcManis/Axiom/blob/master/source/Axiom/Axiom/MainWindow.xaml.cs

---

**Theme** files are in here, they are written in `XAML`
https://github.com/MattMcManis/Axiom/tree/master/source/Axiom/Axiom/Themes

**ViewModel** for Settings 
Theme dropdown menu options
https://github.com/MattMcManis/Axiom/blob/master/source/Axiom/Axiom/ViewModel/ConfigureViewModel.cs

You can copy one of the themes to use as a template and save with a new file name. 
You also have to add the file to the Project inside Visual Studio so it detects it.

---

Then **compile** in Visual Studio to an `exe` as `Release`.

**Comment by Pedroxam** [comment]
Exactly, I needed all these things.
i will try this steps. 
Thanks man.
