### ISSUE TITLE
CLI for File Properties box

### ISSUE THREAD

**Issue by Wakagithub** [MattMcManis/Axiom#25]
Is there a way to use the File Properties box (perhaps even by itself) via a command line?

For example, I want to right-click an MKV (or any media format) in Windows Explorer, then perhaps create one or both of below, to use Axiom's File Properties box/window easily.

1. SendTo icon.

2. Or I could manually create a Shell command in the Registry pointing to Axiom with the approriate options/switches for the File Properties box. Similar to the "Open with Notepad" Registry trick taught on some forums, blogs, etc.

Thanks.

**Comment by MattMcManis** [comment]
Sorry for the late reply, I haven't checked on this for a while.

You can use the File Properties via command line using:

```
ffprobe -i "C:\Path\To\video.mp4" -v quiet -print_format ini -show_format -show_streams
```

That's what Axiom uses and displays it in a Window.

As for integrating it into a shell command, that's not available in Axiom, I am unsure how to do that. But I'm sure that CLI command could be put in a batch file and called somehow when you right click a file.
