### ISSUE TITLE
AMF Option for Hardware Acceleration

### ISSUE THREAD

**Issue by NikoofDeath** [MattMcManis/Axiom#26]
Given that the UI has support for Nvidia-only API's, could AMD's alternative (AMF) be added to the HW Accel dropdown? Maybe also adding a tooltip about the GPU requirements for each.

**Comment by MattMcManis** [comment]
https://www.reddit.com/r/Amd/comments/8eirp4/ffmpeg_40_released_includes_amf_hardware_encoding/

It looks like FFmpeg has the option, but do you know if it requires compiling it from source with certain flags enabled for it to work? I will plan on adding the option in case you have a custom FFmpeg.

You can try this for now, generate a `script` for a normal `mp4`/`mkv` with `x264`/`x265`, that will give you a framework to use. Then manually change the `-c:v libx264` to  `-c:v h264_amf` or `-c:v hevc_amf` and press run. (If using `2 Pass`, make sure to change it in pass 1 and pass 2. I recommend `CRF` over `2 Pass`.)

**Comment by NikoofDeath** [comment]
The official builds have it, and, as you suggest, I've been changing to -c:v h264_amf manually successfully.

**Comment by panther7** [comment]
Same problem for nvidia cards, for HW accel you need: `-c:v hevc_nvenc` or `-c:v h264_nvenc`.

I am for it, dropdown for AMD/Nvidia HW encoder accel.

**Comment by MarcoRavich** [comment]
...and what about Intel QuickSynch ?

**Comment by MattMcManis** [comment]
@NikoofDeath @panther7 

It's taken a while to get to this, but I've released an update with some new options:

- HW Accel `Decode` and `Transcode` menus.
- HW Accel `Decode` option `auto`.
- HW Accel `Transcode` option `AMD AMF` for `x264`/`x265`.
- Video Tab has new Sub Tabs, `Encoding`, `Color`, `Size`, to reduce the vertical scrolling height.

![](https://i.imgur.com/ChhOslZ.png)

These changes could introduce new bugs, you will have to test it out and let me know how it works. Certain HW Accel options may need the required Intel/Nvidia/AMD hardware.
Some HW Accel `Transcode` codecs are only available for `x264`/`x265`.

---

Press the arrow button in Axiom to update through PowerShell, or download from here   
https://github.com/MattMcManis/Axiom/releases

![Update](https://i.imgur.com/mfqw9Mm.jpg)
