### ISSUE TITLE
can you provide for linux?

### ISSUE THREAD

**Issue by ghost** [MattMcManis/Axiom#27]
can you provide this awesome tool for linux ? it's very helpfull I never used such easy tool to manage my own configurations in ffmpeg with such perfection.

**Comment by MattMcManis** [comment]
Thanks, unfortunately the program is written in C# and uses XAML for the GUI. Everything would have to be rewritten from scratch for Linux, this would take too long for me to accomplish at this time.

**Comment by ghost** [comment]
anyway great work I appreciate it so much.

Em sáb, 26 de out de 2019 às 15:43, Matt McManis <notifications@github.com>
escreveu:
