### ISSUE TITLE
Incorrect value for -q:a

### ISSUE THREAD

**Issue by TheRandomLabs** [MattMcManis/Axiom#28]
Axiom generated `-q:a 4,48816` instead of `-q:a 4.48816`, which I assume is due to the fact that my system is set to a European language.

**Comment by MattMcManis** [comment]
Thanks for finding this bug. I have only built and tested the program in American English.
I will see if I can add a filter that always corrects the comma to a period.

**Comment by TheRandomLabs** [comment]
Brilliant!

**Comment by MattMcManis** [comment]
Sorry I was sick for 2 months and got behind on updating this project.

I have released a new version 1.7.8.1. Press the update arrow button in Axiom, or download from here https://github.com/MattMcManis/Axiom/releases

Let me know if it solved the problem.

**Comment by TheRandomLabs** [comment]
Sorry for the late response, but it looks like it's fixed.
