### ISSUE TITLE
 Image Sequence to Video 

### ISSUE THREAD

**Issue by AerialAtom** [MattMcManis/Axiom#3]
Does it do this as well? If so, how can I use it?

**Comment by MattMcManis** [comment]
It does not, I will look into adding it. 

Take a look here 
https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg

Name your images something like `image-001.jpg`, `image-002.jpg`, etc. and put them in a folder.

Run this code with your paths. Adjust frame-rate and quality as needed.
`ffmpeg -start_number 0 -i "C:\test\image-%03d.jpg" -c:v libx264 -vf "fps=24,format=yuv420p" "C:\test\video.mp4"`

Higher Quality
`ffmpeg -start_number 0 -i "C:\test\image-%03d.jpg" -c:v libx264 -preset medium -b:v 2500K -crf 20 -pix_fmt yuv420p -vf "fps=24,format=yuv420p" "C:\test\video.mp4"`
