### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by ZhxChen** [MattMcManis/Axiom#35]
that  need \\ before the colon : (i.e. \\:) and \\\\ in place of single backslashes \ e.g.:

subtitles=C\\:\\\\users\\\\\\\\home\\\\desktop\\\\subs.srt

**Comment by MattMcManis** [comment]
Hi, is this for use with PowerShell?

**Comment by MattMcManis** [comment]
@ZhxChen 

I see, it was for Burn Subtitles. I've fixed the path and tested an srt file. Let me know if it works for you.

I've also fixed some bugs and added new features.

Press the arrow button in Axiom to update through PowerShell, or download from here   
https://github.com/MattMcManis/Axiom/releases

![Update](https://i.imgur.com/mfqw9Mm.jpg)

**Comment by ZhxChen** [comment]
> @ZhxChen
> 
> I see, it was for Burn Subtitles. I've fixed the path and tested an srt file. Let me know if it works for you.
> 
> I've also fixed some bugs and added new features.
> 
> Press the arrow button in Axiom to update through PowerShell, or download from here
> https://github.com/MattMcManis/Axiom/releases
> 
> ![Update](https://camo.githubusercontent.com/93f91a21a41ba815c059ebcd80ccb5145641d8f4/68747470733a2f2f692e696d6775722e636f6d2f6d667177394d6d2e6a7067)

I have done testing and this bug has been fixed. Thanks Reply.
