### ISSUE TITLE
Support for NVENC

### ISSUE THREAD

**Issue by zakx** [MattMcManis/Axiom#4]
Hi,

I've been using Axiom a few times now and I really like it.

Now that I'm encoding larger videos, I'm starting to miss support for hardware encoding (or more specifically, NVENC), see https://trac.ffmpeg.org/wiki/HWAccelIntro#NVENC.

Could you add the option to use h264_cuvid and h264_nvenc?

Thanks!
zakx

**Comment by MattMcManis** [comment]
Sure thing. I'm planning to update the interface and add more options so you can choose profile, pixel format, and filters.

**Comment by MattMcManis** [comment]
@zakx I've upgraded the interface, now there will be more room for additional options. I will plan on adding a hardware encoding toggle under Settings that will enable `h264_cuvid` and `h264_nvenc`.

**Comment by MattMcManis** [comment]
@zakx 

I added a HW Accel dropdown menu under the Format Tab.
To enable it, select a format like `MP4` or `MKV`, set Video Codec to `x264` or `x265`.

![HW Accel](https://i.imgur.com/sJNbPcW.png)  

https://github.com/MattMcManis/Axiom/releases

Let me know if it works correctly. I'm not able to test it, I don't have a compiled FFmpeg that supports it.

***

**x264** uses `h264_cuvid` and `h264_nvenc`
**x265** uses `hevc_cuvid` and `hevc_nvenc`

**DXVA2**
`ffmpeg -hwaccel dxva2 -y -i input.mp4 -c:v h264_cuvid -crf 23 output.mp4`

**CUVID**
`ffmpeg -y -i input.mp4 -c:v h264_cuvid -crf 23 output.mp4`

**NVENC**
`ffmpeg -y -i input.mp4 -c:v h264_nvenc -crf 23 output.mp4`

**CUVID + NVENC**
`ffmpeg -hwaccel cuvid -c:v h264_cuvid -y -i input.mp4 -c:v h264_nvenc -crf 23 output.mp4`
