### ISSUE TITLE
[Bug]: Run button doesn't show any reaction after upgrading to v1.8.3-alpha 

### ISSUE THREAD

**Issue by mjebrahimi** [MattMcManis/Axiom#46]
This problem occurs only if you use an older version and upgrading to _v1.8.3-alpha_.

**Problem Details:**

After adding the Shell feature, because previous versions did not have this feature, the config file (`axiom.conf`) does not contain the `Shell_SelectedItem` setting and the `VM.ConfigureView.Shell_SelectedItem` property will be set to empty in the `ReadConfig` method but in UI it still shows `CMD` selected.

Therefore the `FFmpegStart` method won't do anything (It would have been better to throw an exception or showing MessageBox in the default case of switch statement)

At the end when App is closing and the `ExportConfig` method is called, the `Shell_SelectedItem` setting will not be set (because of empty value) 

This problem is solved when the shell ComboBox (`cboShell`) value changes once that cause set the `VM.ConfigureView.Shell_SelectedItem` property value and saving the setting in axiom.conf on app closing.

**Comment by mjebrahimi** [comment]
Of course, I opened a new issue and explained the cause of the problem.

Thanks again for your support on HW Accel.

**Comment by MattMcManis** [comment]
Thanks for finding this, I had not thought this far ahead for the upgrade process.

For a quick fix,  in `ReadConfig()` I made `Shell_SelectedItem` select `CMD` as default if it has loaded an empty value.

```
// read from conf
VM.ConfigureView.Shell_SelectedItem = conf.Read("Settings", "Shell_SelectedItem");

// default if empty
if (string.IsNullOrEmpty(VM.ConfigureView.Shell_SelectedItem))
{
    VM.ConfigureView.Shell_SelectedItem = "CMD";
}
```

I've released an update. 

I deleted the config and did a test upgrading `v1.7.8.1` to `v1.8.4.1` and it seems to work, both Run and Convert buttons function.

**Comment by MattMcManis** [comment]
Another way I've decided to go. 

I've set null checks for all items in the `ReadConfig()`.

If it imports an `empty` value from `axiom.conf`, it will skip it and let the `ViewModel` `LoadControlsDefaults()` set the default value.

---

ReadConfig()
```
// Shell

// read from conf to temp string
string shell_SelectedItem = conf.Read("Settings", "Shell_SelectedItem");

// skip if value is empty
if (!string.IsNullOrEmpty(shell_SelectedItem) && 
    !string.IsNullOrWhiteSpace(shell_SelectedItem))
{
    // use imported conf value
    VM.ConfigureView.Shell_SelectedItem = shell_SelectedItem;
}
```

LoadControlsDefaults()
```
// load at startup
Shell_SelectedItem = "CMD";
```

---

Let me know if this works for you.

**Comment by mjebrahimi** [comment]
It works now 👍.

This is good way to check the value before set but it would be better if you wrote a static method to prevent you from repeating your code.

In addition the `string.IsNullOrWhiteSpace` method also checks for empty so there is no need to `IsNullOrEmpty`.

**Comment by MattMcManis** [comment]
That's good to know about `string.IsNullOrWhiteSpace`, I thought empty and whitespace each had their own.

I will go through and optimize the code.
