### ISSUE TITLE
[FEATURE REQ] x265 yuvj420p option

### ISSUE THREAD

**Issue by jorgebr** [MattMcManis/Axiom#49]
My Google Pixel 3 encodes videos in HEVC using pixel format `yuvj420p`, but that option does not show up for x265.  I only see, among others, `yuv420p` (without the j).

If I use x264, the option `yuvj420p` does show up. 

I'm not a video tech,  just a user.  Some internet postings suggested that `yuvj420p` may be outdated, but if Google is using it for their Pixel phones, then it must still be valid.  Could you add that option for x265?

I end up always having to manually adjust the script by hand.  There's a definite difference if I instead use `yuv420p` (without the j) -- the darks are greyed out.

Thanks for this wonderful work!

**Comment by MattMcManis** [comment]
It looks like `yuvj420p` is a supported pixel format for `x265` in FFmpeg. I will fix it and release an update soon.

**Comment by MattMcManis** [comment]
@jorgebr 

This has now been fixed in the latest version 1.9.0.0.

**Comment by jorgebr** [comment]
It's there!  Thank you!
