### ISSUE TITLE
Support for Drag and Drop

### ISSUE THREAD

**Issue by Tox86** [MattMcManis/Axiom#6]
Hi that is my suggestion.
![drag drop](https://user-images.githubusercontent.com/7013508/38525291-18539f9c-3c28-11e8-87db-4a23dd219070.gif)

**Comment by MattMcManis** [comment]
I will try to find a way to do it.

**Comment by MattMcManis** [comment]
@Tox86 

I've added the feature, let me know if it works for you.

Download the latest version or press the Update button in the program.
https://github.com/MattMcManis/Axiom/releases/

I had to disable Admin Rights on the program for Drag & Drop to work. Next time you update it an Admin confirmation will popup if it is installed in C:\Program Files.

**Comment by Tox86** [comment]
Thanks. 💯

**Comment by DumbJoe** [comment]
Hmm, can you do the same for locating ffmpeg, ffprobe and ffplay files by just dragging their exe files into the the field in the settings tab?

**Comment by DumbJoe** [comment]
Like this for example, I know I dragged the wrong file to the wrong field on the first attempt...hahaha:

https://i.imgur.com/IucokG3.gif

**Comment by MattMcManis** [comment]
@DumbJoe 

Sure, I'll add it to 1.6.1.0-alpha and release it soon. 

1.6.0.0 has quite a few bug fixes since 1.5.8.0.

**Comment by MattMcManis** [comment]
@DumbJoe 

I've added Drag and Drop to the Settings Program Paths in the latest version v1.6.1.0.

**Comment by DumbJoe** [comment]
> I've added Drag and Drop to the Settings Program Paths in the latest version v1.6.1.0.

Wicked! 

I guess for completion sake, could you also add one for the log? What if you already pre-emptively created an empty text/log file ready to go and all you have to do is just drag and drop the file to the log field and it will automatically choose that file to log any debug info or whatever axiom logs that outputs there? heh...

☺

But yeah, keep up the good work!

**Comment by MattMcManis** [comment]
@DumbJoe 

I will try to add one for the log, it uses folder path and automatically generates `output.log`, but maybe I could change it to a custom file. 

I use the Log Console window to view it temporarily, instead of generating a saved log text file. I created the `output.log` so people could email it to me if they had a problem and I could easily look at their settings.

**Comment by DumbJoe** [comment]
Oh it's just an error debug log? Thought it was ffmpeg log that just printed to a file......
