### ISSUE TITLE
readability problem with high contrast dark mode

### ISSUE THREAD

**Issue by junguler** [MattMcManis/Axiom#60]
hi, i'm using high contrast mode on windows and when i use any themes other than system the buttons are shown as blank

![1](https://user-images.githubusercontent.com/59083599/89742903-551a2780-dab3-11ea-9cb4-504c5c55af81.jpg)

and when i use the system theme the text besides the fields are not readable

![2](https://user-images.githubusercontent.com/59083599/89742919-79760400-dab3-11ea-8f57-75024f8586b8.jpg)

i've been able to somewhat go around this issue by changing themes on every convert but having a dedicated theme that can have both would be very appreciated.

**Comment by MattMcManis** [comment]
Hello, I have been away. I have an announcement here https://github.com/MattMcManis/Axiom/issues/71#issue-757365245

Maybe I can develop a high contrast mode theme.

**Comment by junguler** [comment]
thank you for posting, hoping all is going to be good with you and your family, love and respect.

**Comment by junguler** [comment]
hello again, i have found a high contrast theme online that fixes this issue and this is no longer a problem for me, i'm going to close this issue and let you focus on more important things, thank you for your amazing program.
