### ISSUE TITLE
[Feature Request] convert png files (or multiple images) in a folder to a video

### ISSUE THREAD

**Issue by User198263321** [MattMcManis/Axiom#61]
Every time I do it it gives me an error that it can't find the input file and when I try a script it does not seem to work either.

Can you tell me if this is a thing and if not can you please add it? Thanks!

**Comment by junguler** [comment]
if you have access to git for windows, cmder or any other terminal emulator with bash support you can do this command:
`cat *.png | ffmpeg -f image2pipe -i - output.mp4`
or this one if you want lossless quality
`cat *.png | ffmpeg -f image2pipe -i - -codec copy output.mp4`
i recommend using cmder(full version) in general tho, it's portable and doesn't effect your system in any way.
