### ISSUE TITLE
Crash when using batch function.

### ISSUE THREAD

**Issue by nkh0472** [MattMcManis/Axiom#64]
First, click "batch" button & "INPUT" button, then select source folder;
Second, click "OUTPUT" button and select destination folder;
Then the window of Axiom will disappear without any notice.

Before crashing, the log console display as:
```
Axiom ~ FFmpeg UI (1.9.2.3-alpha)

System Info:
Microsoft Windows 10 企业版 LTSC
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Intel(R) HD Graphics 630 1.074GB
NVIDIA GeForce GTX 1050 Ti 4.294GB
RAM 17.18GB Unknown 2667MHz

Loading Saved Settings...

Config Location: D:\Libraries\axiom.conf

FFmpeg: D:\Libraries\ffmpeg.exe
FFprobe: D:\Libraries\ffprobe.exe
FFplay: D:\Libraries\ffplay.exe
youtube-dl: <auto>

Shell: PowerShell

Log Enabled: False
Log Path: D:\Libraries\

Using CPU Threads: Optimal

Notice: Output Log has not been created yet.
```

**Comment by dephunk** [comment]
Are you on the latest update? I was getting error's with a previous build, but since updating to the latest I've had no issues. Love this GUI

**Comment by nkh0472** [comment]
Yep, as log displayed, I'm using the version of 1.9.2.3-alpha which is currently updated.

Besides, I forget to write, before clicking the "INPUT" button, I click the "batch" button firstly.

> First, click "INPUT" button and select source folder;
> Second, click "OUTPUT" button and select destination folder;
> Then the window of Axiom will disappear without any notice.

**Comment by MattMcManis** [comment]
@nkh0472 

Hello, I have an announcement here https://github.com/MattMcManis/Axiom/issues/71#issue-757365245

I followed your steps, but it did not crash for me. I will look into what might be causing it. I will be releasing an update soon.

**Comment by nkh0472** [comment]
I'm not good at debug, but I used dnspy to run the program, and when it crashed, the dnspy give a notice:
![image](https://user-images.githubusercontent.com/67589323/101230756-253a0400-36e2-11eb-9028-a519efae6901.png)

The message means: Object reference not set to an instance of an object.

**Comment by nkh0472** [comment]
Here is the dump file.
```
D:\Libraries>procdump64 -mm -e 1 -h -t 11884

ProcDump v9.0 - Sysinternals process dump utility
Copyright (C) 2009-2017 Mark Russinovich and Andrew Richards
Sysinternals - www.sysinternals.com

Process:               Axiom.exe (11884)
Process image:         D:\Libraries\Axiom.exe
CPU threshold:         n/a
Performance counter:   n/a
Commit threshold:      n/a
Threshold seconds:     10
Hung window check:     Enabled
Log debug strings:     Disabled
Exception monitor:     First Chance+Unhandled
Exception filter:      [Includes]
                       *
                       [Excludes]
Terminate monitor:     Enabled
Cloning type:          Disabled
Concurrent limit:      n/a
Avoid outage:          n/a
Number of dumps:       1
Dump folder:           D:\Libraries\
Dump filename/mask:    PROCESSNAME_YYMMDD_HHMMSS
Queue to WER:          Disabled
Kill after dump:       Disabled


Press Ctrl-C to end monitoring without terminating the process.

CLR Version: v4.0.30319

[10:50:57] Exception: E0434F4D.System.NullReferenceException ("???????????????")
[10:50:57] Dump 1 initiated: D:\Libraries\Axiom.exe_201205_105057.dmp
[10:50:58] Dump 1 complete: 38 MB written in 0.5 seconds
[10:50:58] Dump count reached.


D:\Libraries>
```
[Axiom.exe_201205_105057.zip](https://github.com/MattMcManis/Axiom/files/5646394/Axiom.exe_201205_105057.zip)

**Comment by MattMcManis** [comment]
I think it might be caused by `outputDir.TrimEnd('\\') + @"\";` adding a slash to a null path. I will release an update soon.

**Comment by MattMcManis** [comment]
I have a test build here if you want to try.

[Axiom.zip](https://github.com/MattMcManis/Axiom/files/5646436/Axiom.zip)

**Comment by nkh0472** [comment]
Wow, no crash anymore. Great!

**Comment by MattMcManis** [comment]
More improvements have been made in the latest build

https://github.com/MattMcManis/Axiom/releases/tag/v1.9.3.2-alpha
