### ISSUE TITLE
Custom video bitrate doesn't work

### ISSUE THREAD

**Issue by ghost** [MattMcManis/Axiom#7]
Changing the video bitrate to custom and setting it, changes the command in "Script", but the video output is always the same bitrate and size.

![2018-05-14_20-31-50](https://user-images.githubusercontent.com/12094600/39997560-eb699604-57b5-11e8-90ff-f2c813c4f9e2.png)

Is there a setting I'm missing?

**Comment by MattMcManis** [comment]
@lucario386 

Does the Script look something like this? 

Maybe the 40K bitrate is too low and ffmpeg is resetting to it's default bitrate.

I tried converting a video to webm with 40K, it ended up encoding at 400K.

```
ffmpeg -y 

-i "C:\Users\Maurice\Desktop\nutshell.mp4" 

-c:v libvpx 
-quality good -cpu-used 0 -b:v 40K -pix_fmt yuv420p 
-map 0:v:0? -map_chapters -1 
-sn 

-c:a libvorbis 
-q:a 6 
-map 0:a:0? 

-map_metadata 0 

-threads 8 

"C:\Users\Maurice\Desktop\nutshell.webm"

```

You could try to delete the part of the script that says `-quality good -cpu-used 0` and then click Run.

**Comment by ghost** [comment]
Yes the script is similar. And yes, seems like it uses some sort of default if the bitrate is too low. I increased it and it used the right bitrate, with or without the `-quality good -cpu-used 0` part.

**Comment by MattMcManis** [comment]
@lucario386 

I have also released a new version and interface.

https://github.com/MattMcManis/Axiom/releases
