### ISSUE TITLE
Will this support mpeg2? Don't see the option. 

### ISSUE THREAD

**Issue by madmexicano** [MattMcManis/Axiom#9]

**Comment by MattMcManis** [comment]
I can add it in the next update. Do you need `.mpg`, `.mp4`, or `.m2v` format?

**For now you can generate a script and edit it:**

1. Format Tab
    Select Container `mp4`

2. Video Tab
    Select Pass `1 Pass`
    Select Quality `High`
    Or use Quality `Custom`, enter a bitrate such as `3000K`
    
    [CRF](https://slhck.info/video/2017/02/24/crf-guide.html) Seems to give low quality for `mpeg2`

    ![quality](https://i.imgur.com/7XyAXiU.png)

3. Press the Script Button

4. Script Window 
    Where it says `-c:v libx264`, change to `-c:v mpeg2video `  (put a space at the end).

5. Change the Output file extension in the script from `.mp4` to `.mpg` if you need.
    Remove `-f mp4` in the script.

6. Press Run

---

**The script will look something like:**

```
ffmpeg -y 

-i "C:\Users\Matt\Videos\video.mp4" 

-c:v mpeg2video 
-preset medium -b:v 2500K -pix_fmt yuv420p 
-vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" 
-map 0:v:0? -map_chapters 0 

-c:s mov_text 
-map 0:s? 

-c:a copy 
-map 0:a? 

-map_metadata 0 

-threads 0 

"C:\Users\Matt\Videos\new video.mpg"
```

**Comment by MattMcManis** [comment]
@madmexicano 

I have updated my post. 

`mpeg2` can use `.mpg`, `.m2v`, `.avi`, `.mp4`, `.mkv` containers. 

`.m2v` is video stream only, no audio. Used for muxing. 

DVD is `mpeg2` / `.mpg` or `.avi`

Mobile is `mpeg4` / `.mpg`, `.avi`, `.mp4`

Modern devices are `x264` / `.mp4`, `.mkv`

**Comment by MattMcManis** [comment]
@madmexicano 

I have added `mpeg2`. Press the update button to update to the latest version.

In the Format Tab select Container `mpg`, `avi`, or `m2v`.

![container](https://i.imgur.com/teLaBxQ.jpg)

In the Video Tab you can select the Codec.

![codec](https://i.imgur.com/sOwdWvU.jpg)

**Comment by madmexicano** [comment]
Thanks for the update. Will try it out.
